name: cpp_checks
on:
  push:
    branches: [ "master" ]
  pull_request:

jobs:
  check-clang-format:
    name: Clang format
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run clang-format style check for C/C++/Protobuf programs.
      uses: jidicula/clang-format-action@v4.11.0
      with:
        clang-format-version: '13'
        check-path: 'master'
        fallback-style: 'Google'